
dubbo:
  application:
    name: user_service1
  registry:
    address: zookeeper://47.106.134.229:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///test1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
